Repository PanarinM/courses_homeworks, pull requests merged in 2018-10, with the labels that each got.

#14 Bolbas
  bolbas_hw/hw1_1.py
  bolbas_hw/hw1_2.py
  bolbas_hw/hwtxt
  bolbas_hw/test
Labels: HW 1

#13 HW2
  Slipchenko/HW2/HW2_1.py
  Slipchenko/HW2/HW2_2.py
  Slipchenko/HW2/HW2_3.py
  Slipchenko/HW2/HW2_4.py
  Slipchenko/HW2/HW2_5.py
Labels: HW 2, python issue, task issue

#5 Hm_1 Belostenko
  Belostenko/HM_1/z1.py
  Belostenko/HM_1/z2.py
Labels: HW 1, python issue

#9 Yaschuk, HomeWorks
  Yaschuk/HW2/1_task/2list_randomlet.py
  Yaschuk/HW2/2_task/dict_logins.py
  Yaschuk/HW2/3_task/stair.py
  Yaschuk/HW2/4_task/pyramide.py
  Yaschuk/HW2/5_task/scratch_5.py
  Yaschuk/scratch.py
  Yaschuk/scratch_1.py
Labels: HW 1, HW 2

#18 [ADD]adding HW 3
  tsarenko/bubble.py
  tsarenko/read_idk.py
  tsarenko/sieve.py
Labels: HW 3, python issue

#22 HW4_1
  Slipchenko/HW4/HW4_1.py
  Slipchenko/HW4/HW4_2.py
Labels: HW 4, python issue

#23 Ushakov's first homework
  P-Ushakov/HW1/HW_1.1.py
  P-Ushakov/HW1/HW_1.2.py
Labels: HW 1, git issue

#19 Slipchenko hw3
  Slipchenko/HW3/HW3_2.py
  Slipchenko/HW3/HW3_3.py
  Slipchenko/HW3/HW_3_1.py
Labels: HW 3

#16 [HM2]Belostenko
  Belostenko/HM_2/hm2_1.py
  Belostenko/HM_2/hm2_2.py
  Belostenko/HM_2/hm2_3.py
  Belostenko/HM_2/hm2_4.py
  Belostenko/HM_2/hm2_5.py
Labels: HW 2, python issue, task issue

#29 Ushakov's HW_3
  P-Ushakov/HW3/HW_3.1.py
  P-Ushakov/HW3/HW_3.2.py
  P-Ushakov/HW3/HW_3.3.py
Labels: HW 3, python issue, syntactic issue

#24 Ushakov's second homework
  P-Ushakov/HW2/HW_2.1.py
  P-Ushakov/HW2/HW_2.2.py
  P-Ushakov/HW2/HW_2.3.py
  P-Ushakov/HW2/HW_2.4.py
  P-Ushakov/HW2/HW_2.5.py
Labels: HW 2, syntactic issue

#28 Ushakov's Hw4
  P-Ushakov/HW4/HW_4.1.py
  P-Ushakov/HW4/HW_4.2.py
Labels: HW 4, python issue

#21 First homework on the new branch test
  Kushnir/HW1/HW1_1.py
  Kushnir/HW1/HW1_2.py
  Kushnir/HW2/HW2_1.py
  Kushnir/HW2/HW2_2.py
  Kushnir/HW2/HW2_3.py
  Kushnir/HW2/HW2_4.py
  Kushnir/HW2/HW2_5.py
  Kushnir/HW3/HW3_1.py
  Kushnir/HW3/HW3_2.py
  Kushnir/HW3/HW3_3.py
  Kushnir/HW4/HW4_1.py
Labels: HW 1, HW 2, HW 3, HW 4, git issue, python issue, syntactic issue
